### ISSUE TITLE
Resolve by hostname

### ISSUE THREAD

**Issue by mfbloom** [osunick/candash#7]
CANServer supports mdns in version 2.1.0. When using your phone as a wifi hotspot you do not know the IP address that CANServer will be assigned but will be able to access the data via http://canserver.local

**Comment by osunick** [comment]
I'm confused. Zeroconf is implemented, so you should be able to tap "scan"
to get the canserver.local broadcast.

**Comment by mfbloom** [comment]
You're right. It does work. Regression issue on my phone with mdns. Why the scan button? Why not just automatically "scan" if no panda does is being received (I wasn't sure what I was even scanning for :) )

**Comment by osunick** [comment]
Simple get unsatisfying answer is that I haven't really gotten around to
designing a good onboarding experience, and the UX in place is really
designed for my testing rather than the best end user experience. I will
definitely get to it, but I figured get the test app out to see if it's
even worth doing (otherwise I only have to build for myself)

**Comment by mfbloom** [comment]
Totally understand! You've done a fantastic job so far!!! I've been using it for a few days now and really enjoying it.
